### ISSUE TITLE
Using curl to fetch lyrics 

### ISSUE THREAD

**Issue by hisacro** [liyasthomas/ludacris#4]
Is there a way to fetch lyrics with curl, something like
```
curl --get -F "title=<-" https://liyasthomas.github.io/ludacris/ 
```
it makes usage much simple..

**Comment by liyasthomas** [comment]
Hi there, I make use of https://lyrics.ovh API to fetch lyrics.
Kindly refer to their [API Doc](http://docs.lyricsovh.apiary.io) for other supported methods.

EDIT: I afraid there's no option to fetch lyrics on a cURL with this API.
